iden3/circom

- code_producers/src/c_elements/c_code_generator.rs
- code_producers/src/wasm_elements/wasm_code_generator.rs
Hi, I was playing around with building a WASM port for Circom 2.0. I noticed though that the slowest part by far was the `merge_code` step (it would hang for nearly 30 seconds before finishing). 
The current implementation is very allocation-heavy as it repeatedly re-allocates and copies strings. Rust 1.3.0 and later support a native Vec.join implementation which will more intelligently allocate a single buffer and copy from the strings in between.
> Faster `merge_code` implementation in code generators

- circom/src/execution_user.rs
- circom/src/input_user.rs
- circom/src/main.rs
- code_producers/src/wasm_elements/wasm_code_generator.rs
While trying to process the logs of circom2, I found that you don't actually write errors to stderr, but instead print them in red on stdout.
This changes the "error" `println` calls to `eprintln` to print on stderr.
> fix: Print errors to stderr

- dag/src/witness_producer.rs
We must delay this removal until we know how to safely remove those same signals in the r1cs file
> Undo removal of custom gates' signals in witness

- code_producers/src/wasm_elements/bls12381/witness_calculator.js
- code_producers/src/wasm_elements/bn128/witness_calculator.js
- code_producers/src/wasm_elements/goldilocks/witness_calculator.js
- code_producers/src/wasm_elements/wasm_code_generator.rs
- compiler/src/intermediate_representation/log_bucket.rs
- compiler/src/intermediate_representation/translate.rs
- parser/src/lang.lalrpop
- program_structure/src/abstract_syntax_tree/ast.rs
- program_structure/src/abstract_syntax_tree/statement_builders.rs
- program_structure/src/program_library/error_code.rs
- type_analysis/src/analyzers/type_check.rs
Fixes https://github.com/iden3/circom/issues/82
This PR adds `log("foo", 1)` syntax to the circom language. The label is then printed when generating a witness with the C++ witness generator. It is very hard to add these labels to the wasm generator, so the label is discarded and only the value is printed when generating with the witness in wasm.
This feature is a huge quality-of-life improvement for large circuit authors, like @yi-sun and other @0xPARC members.
> feat: Allow `log(label, value)` & print labels in C witness generator

- code_producers/src/wasm_elements/common/witness_calculator.js
- compiler/src/intermediate_representation/log_bucket.rs
- constraint_generation/src/execute.rs
This fixes the `log()` printing for wasm. Previously, `log("foo", 1, "bar", 2)` would print as `foo1bar2` but with this change it will log as `foo 1 bar 2`
This also removes the need for `process.stdout` which isn't portable to the browser. I encountered this issue when migrating the log changes to circom_runtime for snarkjs.
> fix: Log messages from wasm with better formatting

- circom/src/compilation_user.rs
- circom_algebra/Cargo.toml
- code_producers/Cargo.toml
- code_producers/src/c_elements/mod.rs
- code_producers/src/lib.rs
- code_producers/src/wasm_elements/mod.rs
- code_producers/src/wasm_elements/wasm_code_generator.rs
- compiler/Cargo.toml
- compiler/src/circuit_design/build.rs
- compiler/src/circuit_design/circuit.rs
- compiler/src/compiler_interface.rs
- constraint_generation/Cargo.toml
- constraint_list/Cargo.toml
- constraint_writers/Cargo.toml
- dag/Cargo.toml
- parser/Cargo.toml
- program_structure/Cargo.toml
- type_analysis/Cargo.toml
Since SnarkJS needs to support all versions of circom, and this project doesn't follow semantic versioning, it would be helpful to include all digits in the version number returned by the `getVersion` export.
This would allow us to do feature switching based on the version of the compiler.
> feat: Add `getMinorVersion` and `getPatchVersion` exports to wasm output

- constraint_generation/src/execute.rs
When an assignment (with <--) is performed in a regular template, and such assignment can be understood as a R1CS constraint, circom warns the user that they may want to add that constraint (and thus using <==). This is not the case for custom templates, where we cannot use <==. This warning was removed for custom templates.
> Removed unnecessary warning for custom templates

- circom/src/execution_user.rs
- constraint_list/src/lib.rs
- constraint_list/src/r1cs_porting.rs
- constraint_writers/src/lib.rs
- dag/src/lib.rs
- dag/src/r1cs_porting.rs
- parser/src/lib.rs
- program_structure/src/program_library/program_archive.rs
When the files are being parsed, it's checked if the file containing the main component (there should be just one of those files in a correct circuit definition) is using the custom templates pragma. That information is used later, when writing the R1CS file, to avoid writing sections 4 and 5 if custom templates are not being used.
> Only printing sections 4 and 5 of the R1CS file when necessary

- mkdocs/docs/getting-started/computing-the-witness.md
JavaScript can only represent non-negative integers accurately up to 2^53, and many applications may have signals with values larger than these.
I edited the getting started section to recommend using strings instead of numbers to prevent future newbies like myself making this mistake.
> Recommend using strings instead of numbers in input.json

- constraint_generation/src/compute_constants.rs
WebAssembly is a 32bit machine, this measures the compile target's ubyte size rather than hard coding the assumption that it is 8 bytes.
> Support non-64bit architectures

- constraint_generation/src/compute_constants.rs
Previous version implied that usize is 8 bytes; use standard num_bigint function that has no such limitation.
> Make circom to build on wasm32

- type_analysis/src/analyzers/unknown_known_analysis.rs
It appears https://github.com/iden3/circom/commit/0d775648c03516328c875d858e0c1b27cd1887c2 introduced some new static analysis that crashes on certain type of circuits that use mutable vars to index component arrays/constraints with this error:
```
thread 'main' panicked at 'Method call in file type_analysis/src/analyzers/unknown_known_analysis.rs line 216',
/Users/nibnalin/Documents/circom/program_structure/src/utils/environment.rs:192:9
```
This patch fixes such issues. I don't quite understand the full details of the static analysis but I believe this check of modified variables should be similar to the check for `IfThenElse`, which correctly includes a `has_variable` check already, so that check is also required here.
An example circuit that reproduces the crash is in this gist when …
> Fix compiler panic on exit modified variables not in env

- mkdocs/docs/circom-language/variables-and-mutability.md
Hi, I just add the missing semicolon in the Variables & Mutability document page. Thank you
> Fix small typo in variables and mutability documentation

- code_producers/src/c_elements/c_code_generator.rs
- code_producers/src/c_elements/common/circom.hpp
The code generated for C++ when using parallel components produces a core dump:
```
./final ~/zkevm-prover/final_proof.zkin.json final.wtns
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
This is due to how memory is freed, I have converted the deletes to array, added a check to avoid freeing if they have not been allocated, and also the initialisation of the pointers to null, this seems to fix the problem
> fix generate_function_release_memory_component function

- program_structure/src/program_library/error_definition.rs
Reports are public but not readable. This PR makes it easy for people developing tools for circom to use information from reports generated by the library (e.g. parsing, AST analysis)
> fix: Report visibility

- mkdocs/docs/circom-language/code-quality/inspect.md
The current `inspect.md` contains some code blocks starting and ending with a whitespace followed by three backticks.
This makes the [rendered result](https://docs.circom.io/circom-language/code-quality/inspect/) break. 
Removing the whitespace fixes the issue.
> Fix inconsistencies on inspect.md markdown format

- type_analysis/src/analyzers/type_check.rs
It seems that the report code NonCompatibleBranchTypes was accidentally not covered. I checked if any other report codes were left out and as far as I can tell this is the only one.
The following code causes Circom to panic
```circom
pragma circom 2.1.5;
function A(t) {
return t == 1 ? [1, 2, 3] : 4;
}
```
```circom
pragma circom 2.1.5;
include "./a.circom";
template B() {
var a0[3] = A(1);
}
component main = B();
```
run:
```
circom b.circom
```
> bug fix: cover NonCompatibleBranchTypes

- compiler/src/intermediate_representation/call_bucket.rs
- compiler/src/intermediate_representation/store_bucket.rs
In some cases asserts are disabled by cpp compiler and operation (subcomponent counter decrease) is not executed.
Fixes the problem with cpp witnesscalc reported here: https://github.com/0xPolygonID/witnesscalc/issues/4#issuecomment-1561302651
In general would be good to switch from asserts to exceptions I think.
> Move subcomponent counter decrease operation outside of assert

- code_producers/src/c_elements/bls12381/fr.hpp
- code_producers/src/c_elements/bn128/fr.hpp
There was error while doing `make` command in generated cpp directory. Error example:
```
g++ -c fr.cpp -std=c++11 -O3 -I.
In file included from fr.cpp:1:
./fr.hpp:71:50: error: unknown type name 'uint'; did you mean 'int'?
void Fr_str2element(PFrElement pE, char const*s, uint base);
^~~~
int
fr.cpp:56:51: error: unknown type name 'uint'; did you mean 'int'?
void Fr_str2element(PFrElement pE, char const *s, uint base) {
^~~~
int
```
> fix c++ witness code producer on macos with clang 14.0.0

- mkdocs/docs/background/background.md
The equation `a*b - c = out` is missing `mod 7` at the end.
> docs: background.md typo

- mkdocs/docs/background/background.md
Changed `﻿a*b - c = out mod 7` to `a*b + c = out mod 7`, which is the equation illustrated in the document.
> fix: background.md typo

- mkdocs/docs/circom-language/constraint-generation.md
The `<== `operator  seems first assigns, then adds a constraint.
> fix:constraint-generation doc

- compiler/src/intermediate_representation/address_type.rs
- compiler/src/intermediate_representation/branch_bucket.rs
- compiler/src/intermediate_representation/compute_bucket.rs
- compiler/src/lib.rs
- parser/Cargo.toml
To use Circom as a library from https://github.com/iden3/circom-witnesscalc, it would be great to make few types public. And add a lexer feature to `lalrpop-util`
Also I've fixed some issuers with formatting of internal structs. 
And make OperatorType hashable to be able to use it as a Key in Map.
> Make some types public to use Circom as a library

- mkdocs/docs/circom-language/tags.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "compiler does never" to "compiler never does".
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- mkdocs/docs/circom-language/code-quality/code-assertion.md
Hi! I fixed dead link in docs
https://docs.circom.io/circom-language/code-quality/code-assertion/
404: https://docs.circom.io/circom-language/code-quality/circom-insight/unknowns
Correct: https://docs.circom.io/circom-language/circom-insight/unknowns
> docs: update dead link

- type_analysis/src/analyzers/custom_gate_analysis.rs
I'm not entirely certain if this is a bug, but the parameter order here seems different from other function calls.
> fix: correct error/warning parameter order in if-case

- mkdocs/docs/circom-language/buses.md
A typo in the variable name "ouputs". It should be corrected to "outputs" to ensure consistency and accuracy in the codebase.
This change has been made and tested.
> fix: Fix typo in variable name Update buses.md

- RELEASES.md
- mkdocs/docs/circom-language/control-flow.md
- mkdocs/docs/circom-language/identifiers.md
- mkdocs/docs/circom-language/the-main-component.md
The unexpected marks might confuse readers and be distracted by them. Also some editors might not render correctly depending on the software or platform used, appearing as gibberish or causing formatting problems.
> chore: fix quotation marks

- mkdocs/docs/background/background.md
- mkdocs/docs/circom-language/anonymous-components-and-tuples.md
- program_structure/src/utils/memory_slice.rs
- type_analysis/src/decorators/constants_handler.rs
This pull request addresses several minor typographical errors in both documentation and source code files to improve clarity and readability.
1. **background.md**: Corrected "an specific" to "a specific."
2. **anonymous-components-and-tuples.md**: Replaced "an statement" with "a statement."
3. **memory_slice.rs**: Fixed "a element" to "an element."
4. **constants_handler.rs**: Changed "a expression" to "an expression."
> Fix typos in documentation
